import type {Metadata} from 'next'
import {Nunito} from 'next/font/google'
import './globals.css'

const nunito = Nunito({
    subsets: ['latin'],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={`${nunito.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    )
}
